### ISSUE TITLE
Poker NPC

### ISSUE THREAD

**Issue by merung** [Illarion-eV/Illarion-Content#112]
Re-implement vilarion's poker NPC, adjusted to the new module system, and changed lua functions

**Comment by EviePryler** [comment]
Tested with Slightly the poker NPC in development server.  First thing I noticed was lack of response to triggers like hello, name, job.  That might be in the works also think npc needs something telling you how much big and small blinds are, that things are counted in silver (I think this was it), and what the basic rules of the game are (or somewhere in game to find this).  I tried using emotes to answer the prompts as a normal rp'r would do. I had issues getting the npc to acknowledge any raise put in an emote.  Emotes for call and check worked. I need to test more on those factors that require a number also.  Is there anyway to make it freer on word choice?

**Comment by Quirkily** [comment]
Tested the poker NPC in the development server with EviePryler...  First thought... I could grow addicted to this!

Concerns:
1- The first cards shown... These are to determine who will deal, high card deals. Nothing says this. I thought the card was the first card in my hand and then I was asked to place a blind. It was confusing, especially since it seemed to disappear from my hand. Along with this, non poker players won't know what the red chip moving around the table is for either. That though, can be learned in game from other players.
2 - Emotes for raise... "/me raises to 1000000" does not work. It did not like the 's' at the end of raise.
3 - I never knew the total of the pot until the end, then I don't even know what it is unless I win. Ideally, a player should know every round exactly how much is in the pot. After Melissa tells us what cards are available, something should also be posted to each player about the total amount in the pot at that time. 
4 - Normally, when playing poker, we can see roughly how much each player has in front of them. I didn't even keep track of how much I had. I'm not sure this can or needs to be changed, but thought I should mention it.

It's actually a lot of fun, but there is so much text scrolling that it becomes confusing rather fast... and this is with just two players. I have to wonder if it will be worse with more playing. Add to that a need to actually know your seat number and pay attention to those numbers being called. Then, add players talking and emoting and it could be difficult. Especially for those not speaking in their native language.  Because of that, I think we need a large group test.

**Comment by brightrim** [comment]
https://discord.com/channels/401855954272124940/693091825405263893/998912699343843419

- Lacking immersion
- Too much text spam
- Would likely require a custom GUI to actually work properly
- Too many unresolved issues (as seen in comments above) with no easy solution
- Delays other features of the Hemp Necktie Underground from being made available

Hence resulting in https://github.com/Illarion-eV/Illarion-Content/issues/388

Potential to be reopened later if we 1. have a dev willing to put in the work and 2. the tools to feasibly even make a poker system work without all the flaws this one sadly has
