### ISSUE TITLE
NPC Fijanna Squall

### ISSUE THREAD

**Issue by slightlycomatose** [Illarion-eV/Illarion-Content#155]
Following relocation she needs greater purpose in life.

Key tasks:
Relocate NPC Fijanna Squall to 661 301 0
Development of themed quest line

Proposal:
Witch to send characters in search of rare items from specific locations on map.

**Comment by Quirkily** [comment]
Quest Set-up summary
--
As set up now, there will be a main quest line, followed by a daily quest. The idea is to send people all over illarion looking for items or buying items from others who can find them. 
 
The main quest line will be 12 steps:
3 steps items are obtained from normal means... like dragon eggs and ice leaf herb.
3 steps are quest only items collected in dungeon areas, like the thieves den etc.
7 steps are found by anyone in game and used or sold to those needing them.
For instance, items will be ultra-rare and found while farming, hunting, fishing, herbing, etc.
This is a total of 13 steps because one step is a two-part step and falls into 2 different categories.

This is just my initial thoughts on the witch NPC. Please feel free to comment on how to improve 
Thanks!

**Comment by Brightrim** [comment]
Was any script work done for this?
Is this change still wanted?

**Comment by Brightrim** [comment]
Relocated to the designated position.

**Comment by slightlycomatose** [comment]
To await repurposing and review
