### ISSUE TITLE
Lift string length limitation for parchments and bulletins

### ISSUE THREAD

**Issue by estralis** [Illarion-eV/Illarion-Content#163]
Vilarion has changed scriptvars from char varying to text. We can now allow longer texts in parchments. A reasonable limit based on client display needs to be found and defined in the scripts.

**Comment by Brightrim** [comment]
I decided to have a look at this since it's been untouched for a couple of years now.
The bulletin board length is currently capped at 986. A normal 1920x1080p monitor could fit in double of that easily, but even if that cap is extended it seems to have a natural cap at around 1000~ characters. Not sure if that is set at a client/server level or if that is the new limit of what can be stored in ScriptVars. Using a workaround we could up this to 2000 if we want.
Meanwhile the parchment text is saved as a playeritem_datavalue which is still limited to 255 chars.
I did however find a workaround to allow parchments to hold whatever length of string we want by using multiple datavalues. Here's a parchment that has 2000 characters + a signature :
https://i.gyazo.com/ff108652b50bdecff81c6cd3fd7f84af.png
