### ISSUE TITLE
Tag broken items as [BROKEN] and make them useless rather than deleting them

### ISSUE THREAD

**Issue by estralis** [Illarion-eV/Illarion-Content#182]

**Comment by estralis** [comment]
Items to consider: Tools, wands, weapons, armour
Pick axes and shovels for digging
Ropes

**Comment by slightlycomatose** [comment]
Informed on breakage of tool (issue with double inform identified in #185 due to action sequence).
Broken tool easily distinguishable by name and durability.
Functionality removed and appropriate inform provided.
Tool can subsequently be repaired to recover use.
Gems retained and recoverable from broken tool.
Further testing / discussion required to determine associated risk.
