### ISSUE TITLE
Bugs in money changers

### ISSUE THREAD

**Issue by estralis** [Illarion-eV/Illarion-Content#218]
https://illarion.org/community/forums/viewtopic.php?f=3&t=42717

**Comment by Kerruan** [comment]
Notes: 
-  Amount can only be set to 100: 
You can set the amount to 250, that value is enforced on client side.
- If you buy Coppers and you have Coppers, nothing really happens:
  What should happen here? Besides that buystack of copper should be maybe 100 instead of 1 in general?
-  Cheating  buy 1 Copper, pay 1 Silver:
  At least I could not reproduce that, can someone verify?

**Comment by estralis** [comment]
Closed per Discord discussion in #testing. Cheating could not be reproduced. Increase of buystack to 100 was tested and not found helpful as it prevents "buying" any other number than 100 copper coins.
