### ISSUE TITLE
Redo "A Book About Your God" Quest

### ISSUE THREAD

**Issue by KayMD** [Illarion-eV/Illarion-Content#234]
Quest is currently disabled, but players would like the ability to still get these books. 

Originally this quest was started through a bizarre lookAt trigger. This was then removed and an NPC-based trigger was drafted and given to two of the priest NPCs.  The draft was later removed, fully disabling the quest. We need to figure out how we want to run this quest.

The quest itself has issues: you run a circle to every library for no reason just to shell out 5 gold for a book. That is.... not a real quest.  If we want to keep a quest structure to give out the books, the steps should be reconsidered. Alternatively, the book could just be given away when you devote for the first time.

**Comment by osadchiyilya** [comment]
Some considerations:
1. Players banned from some/all of the towns should still be able to acquire the book. This contradicts both running around libraries (though maybe it skips banned towns) and starting by NPCs. Though maybe they can buy from other players, or there would be a book seller NPC that sells these books for higher price than what will be in the quest.
2. This book (but not necessary quest completion) may become a requirement for becoming a priest. Also might be used as the item that activates priest spells.
3. Perhaps instead of 5gold-after-running-around, the quest could be to collect materials for a librarian to make a copy of the book? Some leather for pages, metal and wood for cover, ink, quill. Maybe also some god-specific item, like wine for Adron etc.

**Comment by brightrim** [comment]
https://discord.com/channels/401855954272124940/401866115380412417/1194809152959168593
