### ISSUE TITLE
Attribute limits result in incorrect messages when using the lockpicks

### ISSUE THREAD

**Issue by estralis** [Illarion-eV/Illarion-Content#325]
Whenever I want to set attributes using the lockpicks that are out of the normal range for characters, I get an error message but also a confirmation that the attribute was changed - what it wasn't. This is confusing.

Also, for testing purposes, I sometimes want to set attributes to extreme values. This I cannot do except I edit the database what is clumsy. I propose to allow attributes outside the normal range for admin characters.

**Comment by Brightrim** [comment]
I agree. The limit is very bothersome for testing. I see no reason why admin characters shouldn't be exempt from the stat limits the GM tool imposes.

Also I looked into the script: for some reason the "return" after the error message was commented out. That seems to be all there is to the double message.

**Comment by Brightrim** [comment]
The stat limits can be surpassed, while keeping the limit for non admin characters, by changing it from "setBaseAttribute" to "setAttrib" as the former does not allow setting it beyond the limit server-side. Neither can be saved, either, as the baseAttribute changes can only be saved if they are within both the total stat limit and individual stat limits, and the current code does not attempt to save the stat changes made. For this to be reflected properly in the selection of stats, it would also have to read the temporary stats instead of baseAttributes. Would this be a desired change, then?

**Comment by Brightrim** [comment]
Will push it along with the fix to the double inform, so the actual code changes I'm talking of are visible for review and testing. Can always simply be reverted or changed if a different approach is wanted.
